config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories
  devise_for :users

  root 'articles#index'
  
  resources :articles
  resources :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates_presence_of :title ,:body
	belongs_to :article
	belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :authenticate_user! , only: [:create, :destroy]
load_and_authorize_resource
	def create
			@comment = Comment.new(comment_params)
			@comment.user_id = current_user.id 
			@comment.save
	end

	def show
		@comments = Comment.where('user_id = ?', current_user)
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
	end


	private

	def comment_params
		params[:comment].permit(:title, :body, :article_id)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.js.erb
var outerDiv = document.createElement('div');
var innerDiv = document.createElement('div');
outerDiv.setAttribute("class","media");
outerDiv.setAttribute("id","comment_<%=@comment.id %>");

innerDiv.setAttribute("class","media-left"); 

var img = document.createElement('img');
img.setAttribute("src","http://lorempixel.com/64/64/people/");
img.setAttribute("alt","Dummy image");
img.setAttribute("class","img-rounded");
innerDiv.appendChild(img);

var divMedia = document.createElement('div');
divMedia.setAttribute("class","media-body");

var header = document.createElement('h4');
header.setAttribute("class","media-heading");

var text = document.createTextNode("<%=@comment.title%>");
header.appendChild(text);

var body = document.createTextNode("<%=@comment.body%>");
divMedia.appendChild(header);
divMedia.appendChild(body);

var anchor = document.createElement('a');
anchor.setAttribute("data-confirm","Are you sure?");
anchor.setAttribute("class","btn btn-sm");
anchor.setAttribute("data-remote","true");
anchor.setAttribute("rel","nofollow");
anchor.setAttribute("data-method","delete");
anchor.setAttribute("href","/comments/<%=@comment.id%>");

var icon = document.createElement('i');
icon.setAttribute("class","glyphicon glyphicon-trash");

anchor.appendChild(icon);
divMedia.appendChild(anchor);

outerDiv.appendChild(innerDiv);
outerDiv.appendChild(divMedia);

$('#comments_section').append(outerDiv);
$('#comment_title').val("");
$('#comment_body').val("");

app/views/comments/destroy.js.erb
//var commentHandle = document.getElementById()

$('#comment_<%=@comment.id%>').slideUp();

app/views/comments/show.html.erb
<h2> Listing Your Comments </h2>

<ul>
<% @comments.each do |comment| %>
<li>(article)-><%= link_to comment.article.title , article_path(comment.article)%>
	<p>(comment)-><%= comment.title %>(<%= comment.body %>) - <%= link_to "delete comment", comment_path(comment), method: :delete , data: {confirm: "Are You Sure?"} %> </p>
</li>
<% end %>
</ul>