config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories
  devise_for :users

  root 'articles#index'
  
  resources :articles
  resources :comments
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :article_categories
	has_many :articles,through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @category = Category.new
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<h3>Add Category</h3>

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="col-md-12"> 
  <div class="page-header"> 
    <h2>Listing Categories</h2>
  </div>
</div>


<div class="col-md-8">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to category ,class: "btn btn-sm" do%>
            <i class="glyphicon glyphicon-eye-open"></i>
            <% end %>
          </td>
          <td><%= link_to edit_category_path(category) ,class: "btn btn-sm" do%>
            <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
          </td>
          <td><%= link_to category, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-sm" do %>
          <i class="glyphicon glyphicon-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to new_category_path ,class: "btn btn-primary" do %><!-- syntax to add glyphicon inside the link-->
    <i class="glyphicon glyphicon-plus"></i> Add category
  <% end %>

</div>

<div class="col-md-4">  
    <!-- this can be used further for displaying it in the right of table -->
    <%= render 'form' %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<div class="col-md-6">
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

</div>

app/views/categories/show.html.erb
	
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<strong>Listing Articles</strong>
	<ul><% @category.articles.each do |article| %>
		<li><%= link_to article.title ,article_path(article)%></li>
	<% end %>
	</ul>


<% if user_signed_in? %>
	<% if can? :edit, Category %>
<%= link_to 'Edit', edit_category_path(@category) %> |
	<% end %>
<%= link_to 'Back', categories_path %>
<% end %>